"""Create all initial tables with constraints

Revision ID: 6bf155581d2b
Revises: 
Create Date: 2026-07-29 20:17:19.676270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf155581d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_estate_name')
    )
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estate_id', 'name', name='uq_court_name_per_estate')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estate_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('main_gate','court_gate')", name='check_checkpoint_type_valid'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.String(length=20), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'slot_number', name='uq_slot_number_per_court')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('host_resident_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_category', sa.String(length=20), nullable=False),
    sa.Column('owner_resident_id', sa.Integer(), nullable=True),
    sa.Column('owner_visitor_id', sa.Integer(), nullable=True),
    sa.Column('registered_at_checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(owner_resident_id IS NOT NULL AND owner_visitor_id IS NULL) OR (owner_resident_id IS NULL AND owner_visitor_id IS NOT NULL)', name='check_vehicle_single_owner_type'),
    sa.ForeignKeyConstraint(['owner_resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['owner_visitor_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['registered_at_checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('checkpoint_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.CheckConstraint("action IN ('entry','exit')", name='check_log_action_valid'),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('parking_slot_id', sa.Integer(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('parked_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('parked','moved','left')", name='check_parking_status_valid'),
    sa.CheckConstraint('left_at IS NULL OR left_at > parked_at', name='check_left_after_parked'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['parking_slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocking_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocking_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('blocked_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('blocking_parking_record_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint('blocking_vehicle_id != blocked_vehicle_id', name='check_incident_distinct_vehicles'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= reported_at', name='check_resolved_after_reported'),
    sa.ForeignKeyConstraint(['blocked_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['blocking_parking_record_id'], ['parking_records.id'], ),
    sa.ForeignKeyConstraint(['blocking_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('parking_record_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['parking_record_id'], ['parking_records.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocking_incident_id', sa.Integer(), nullable=False),
    sa.Column('recipient_resident_id', sa.Integer(), nullable=True),
    sa.Column('recipient_visitor_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.CheckConstraint('(recipient_resident_id IS NOT NULL AND recipient_visitor_id IS NULL) OR (recipient_resident_id IS NULL AND recipient_visitor_id IS NOT NULL)', name='check_notification_single_recipient'),
    sa.ForeignKeyConstraint(['blocking_incident_id'], ['blocking_incidents.id'], ),
    sa.ForeignKeyConstraint(['recipient_resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['recipient_visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('movement_history')
    op.drop_table('blocking_incidents')
    op.drop_table('parking_records')
    op.drop_table('checkpoint_logs')
    op.drop_table('vehicles')
    op.drop_table('visitors')
    op.drop_table('users')
    op.drop_table('residents')
    op.drop_table('parking_slots')
    op.drop_table('checkpoints')
    op.drop_table('courts')
    op.drop_table('estates')
    # ### end Alembic commands ###
